# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186b0fe3a7b00a9b40312e32a6982c90a868742c6bfeea6a9426dee049a4b3e4ce3c8fa6c240615728dfd0b9a28d3f9d3edf7442e1368a6647d196410e502587

test:
  secret_key_base: 35f136ebf01c2d3b3a7ee7164a3c6d1e076e01e5322cc4212c0c08c05b1d81e1f753233977f22592a53e6723c801378a3dbf35b846dcae5d08e94080f150a6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
